FROM php:8.2-fpm-alpine

WORKDIR /var/www/application

# php packages
RUN apk add --no-cache \
    curl \
    git \
    build-base \
    zlib-dev \
    oniguruma-dev \
    autoconf \
    bash \
    libzip-dev \
    linux-headers \
    nodejs \
    npm \
    && docker-php-ext-install pdo pdo_mysql

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN chown -R www-data:www-data /var/www/application \
    && chmod -R 755 /var/www/application

# port 9000 PHP-FPM
EXPOSE 9000

# run PHP-FPM
CMD ["php-fpm"]
