version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/application
  php:
    build:
      context: ./docker/php
      dockerfile: DockerFile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./src:/var/www/application
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - mysql.env